[[constraint]]
  branch = "master"
  name = "github.com/c2stack/c2g"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/gosigar"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "1.3.6"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/anko"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"
